### ISSUE TITLE
go ngrok 2.0?

### ISSUE THREAD

**Issue by vvo** [rase-/zuul-ngrok#4]
Did you try ngrok 2.0? https://github.com/bubenshchykov/ngrok

Is it worth to switch?

**Comment by cristiandouce** [comment]
FYI @rase- `ngrok@0.1.98` install is failing. Maybe not it's worth updating the version.

**Comment by vvo** [comment]
careful because tunnels are no more available without a token, see https://github.com/bubenshchykov/ngrok/issues/34

**Comment by bubenshchykov** [comment]
yes guys we are currently stuck in a limbo - ngrok 1 looks like no more supported (or bins moved away) and ngrok 2 has tricky tunnels issue which u mentioned here

I'm trying to get a workaround from Alan the ngrok creator, but have no estimate for now
